# Based on
# - https://github.com/srggrs/assign-one-project-github-action

name: Auto Assign issue to Project(s)

on:
  issues:
    types:
      - reopened
      - opened
env:
  GITHUB_TOKEN: ${{ secrets.SENZING_GITHUB_ACCESS_TOKEN }}
  REPO_URL: ${{ github.event.repository.url}}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    steps:
    - name: Assign issues in repo with topics to repositories
      uses: Senzing/github-action-add-issue-to-project@main
      with:
        project1: 'https://github.com/orgs/Senzing/projects/2'
        project2: 'https://github.com/orgs/Senzing/projects/6'
        topic1: 't-comm'
        topic2: 't-ast'
        column_name: 'Backlog'
